name: HTML Validate

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    validate_html:
        runs-on: ubuntu-latest

        steps:

            - name: checkout code
              uses: actions/checkout@v4

            - name: validate html
              uses: Cyb3r-Jak3/html5validator-action@v7
              with:
                root: .
            - name: Success message
              run: echo "✅ HTML is valid"      

